### ISSUE TITLE
Error: Ember.ENV should be an object

### ISSUE THREAD

**Issue by edborden** [kristianmandrup/ember-cli-emberscript#5]
On a newly generated app, I've got the following package.json:

```
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "git://github.com/ember-cli/ember-cli.git#master",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-emberscript": "git://github.com/kristianmandrup/ember-cli-emberscript#master",
    "ember-cli-emblem-hbs-printer": "^0.2.0",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-less": "^1.2.0",
    "ember-cli-qunit": "0.3.8",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.15",
    "ember-export-application-global": "^1.0.2",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}
```

And this is what I get when I build:

```
assertion failed: Ember.ENV should be an object.
Error: assertion failed: Ember.ENV should be an object.
    at Object.Ember.assert (C:\Users\borde_000\Desktop\trapsmart\client\node_mod
ules\ember-cli-emberscript\node_modules\broccoli-ember-script\node_modules\ember
-script\lib\ember-runtime.js:52:20)
    at C:\Users\borde_000\Desktop\trapsmart\client\bower_components\ember\ember-
template-compiler.js:182:11
    at requireModule (C:\Users\borde_000\Desktop\trapsmart\client\bower_componen
ts\ember\ember-template-compiler.js:66:65)
    at requireModule (C:\Users\borde_000\Desktop\trapsmart\client\bower_componen
ts\ember\ember-template-compiler.js:62:24)
    at C:\Users\borde_000\Desktop\trapsmart\client\bower_components\ember\ember-
template-compiler.js:7365:1
    at Object.<anonymous> (C:\Users\borde_000\Desktop\trapsmart\client\bower_com
ponents\ember\ember-template-compiler.js:7367:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by edborden** [comment]
@kristianmandrup Any help getting this to work with Ember >1.9 and Ember-CLI >1.7?  Are you still using this in production?

**Comment by kristianmandrup** [comment]
I'm not using Ember anymore. Sorry. Please ask Ember team about breaking changes

**Comment by kristianmandrup** [comment]
http://emberjs.com/guides/configuring-ember/feature-flags/

A global `EmberENV` object will be used to initialize the `Ember.ENV` object... ???

**Comment by asux** [comment]
Have same error. @edborden, how you fixed this?

**Comment by edborden** [comment]
This library, `"broccoli-ember-script": "git://github.com/kolybasov/broccoli-ember-script"`, I'm using with ember-cli@2.3.
